version: '3'

services:  
  weather_history:
    build: "."
    command: python -u app.py               
    external_links:
      - postgres
    networks:
      - mynet

networks:
  mynet:
    external:
      name: mynet          